### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by sylvainmetayer** [sylvainmetayer/sieve-connect-docker#1]
- [ ] https://github.com/juan131/dockerfile-best-practices#how-to-use-this-tutorial
- [ ] Badge Builds/failure
- [ ] Docs sieve connect basic commands
